const drugData = [
    { id: 1, name: '3-Methylindole' },
    { id: 2, name: '3-Methyl-methcathinone' },
    { id: 3, name: 'mephedrone' },
    { id: 4, name: 'Abamectin' },
    { id: 5, name: 'Acetaminophen' },
    { id: 6, name: 'Acetylsalicylic acid' },
    { id: 7, name: 'Albendazole' },
    { id: 8, name: 'Albendazole (sulfoxide metabolite)' },
    { id: 9, name: 'Albendazole (sulfone metabolite)' },
    { id: 10, name: 'Albendazole Sulfoxide' },
    { id: 11, name: 'Albendazole Sulfoxide (sulfone metabolite)' },
    { id: 12, name: 'Albendazole oxide (- enantiomer)' },
    { id: 13, name: 'Albendazole oxide (+ enantiomer)' },
    { id: 14, name: 'Aminophylline' },
    { id: 15, name: 'Clavulanic acid' },
    { id: 16, name: 'Amoxicillin' },
    { id: 17, name: 'Apomorphine' },
    { id: 18, name: 'Articaine hydrochloride' },
    { id: 19, name: 'Avilamycin' },
    { id: 20, name: 'Azithromycin' },
    { id: 21, name: 'Bisphenol A' },
    { id: 22, name: 'Buprenorphine' },
    { id: 23, name: 'Butafosfan' },
    { id: 24, name: 'Butorphanol tartrate' },
    { id: 25, name: 'Caffeine' },
    { id: 26, name: 'Caffeine (paraxanthine metabolite)' },
    { id: 27, name: 'Caffeine (theobromine metabolite)' },
    { id: 28, name: 'Caffeine (theophylline metabolite)' },
    { id: 29, name: 'Carbetocin' },
    { id: 30, name: 'carprofen' },
    { id: 31, name: 'Cefacetrile' },
    { id: 32, name: 'Cefonicid' },
    { id: 33, name: 'Cefoperazone' },
    { id: 34, name: 'Cefquinome' },
    { id: 35, name: 'Ceftiofur (desfuroylceftiofur metabolite)' },
    { id: 36, name: 'Ceftiofur' },
    { id: 37, name: 'Ceftriaxone' },
    { id: 38, name: 'Cefuroxime' },
    { id: 39, name: 'Chloramphenicol' },
    { id: 40, name: 'Chlorpheniramine' },
    { id: 41, name: 'Chlortetracycline hydrochloride' },
    { id: 42, name: 'Chlortetracycline' },
    { id: 43, name: 'Ciprofloxacin' },
    { id: 44, name: 'Colistin' },
    { id: 45, name: 'Cyadox' },
    { id: 46, name: 'Cyanocobalamin' },
    { id: 47, name: 'Cyclosporine' },
    { id: 48, name: 'Danofloxacin' },
    { id: 49, name: 'Deoxynivalenol' },
    { id: 50, name: 'Derquantel' },
    { id: 51, name: 'Detomidine' },
    { id: 52, name: 'Diaveridine' },
    { id: 53, name: 'Diclofenac' },
    { id: 54, name: 'Dicobalt edetate' },
    { id: 55, name: 'Difloxacin' },
    { id: 56, name: 'Diflubenzuron' },
    { id: 57, name: 'Doramectin' },
    { id: 58, name: 'Doxapram' },
    { id: 59, name: 'Doxapram (keto-doxapram metabolite)' },
    { id: 60, name: 'Doxorubicin (doxorubicinol metabolite)' },
    { id: 61, name: 'Doxorubicin' },
    { id: 62, name: 'Doxycycline' },
    { id: 63, name: 'Enilconazole' },
    { id: 64, name: 'Enrofloxacin' },
    { id: 65, name: 'Enrofloxacin (ciprofloxacin metabolite)' },
    { id: 66, name: 'Epinephrine' },
    { id: 67, name: 'Ertapenem' },
    { id: 68, name: 'Erythromycin' },
    { id: 69, name: 'Estradiol-17B' },
    { id: 70, name: 'Progesterone' },
    { id: 71, name: 'Famotidine' },
    { id: 72, name: 'Febantel (fenbendazole metabolite)' },
    { id: 73, name: 'Febantel (sulfoxide metabolite)' },
    { id: 74, name: 'Febantel (sulfone metabolite)' },
    { id: 75, name: 'Fenbendazole' },
    { id: 76, name: 'Fenbendazole (amine metabolite)' },
    { id: 77, name: 'Fentanyl' },
    { id: 78, name: 'Fentanyl citrate' },
    { id: 79, name: 'Fentanyl (N-[1-(2-phenethyl-4piperidinyl)maloanilinic acid metabolite)' },
    { id: 80, name: 'Fexofenadine' },
    { id: 81, name: 'Finasteride' },
    { id: 82, name: 'Firocoxib' },
    { id: 83, name: 'Flecainide' },
    { id: 84, name: 'Florfenicol' },
    { id: 85, name: 'Florfenicol (florfenicol amine metabolite)' },
    { id: 86, name: 'Ketoprofen (R- enantiomer)' },
    { id: 87, name: 'Ketoprofen (S+ enantiomer)' },
    { id: 88, name: 'Flunixin' },
    { id: 89, name: 'Flunixin meglumine' },
    { id: 90, name: 'Flunixin (5-hydroxy flunixin metabolite)' },
    { id: 91, name: 'Fosfomycin' },
    { id: 92, name: 'Furosemide' },
    { id: 93, name: 'Gamithromycin' },
    { id: 94, name: 'Gentamicin' },
    { id: 95, name: 'Halofuginone' },
    { id: 96, name: 'HI-6' },
    { id: 97, name: 'Hydrochlorothiazide' },
    { id: 98, name: 'Hydroxocobalamin hydrochloride' },
    { id: 99, name: 'Ibafloxacin' },
    { id: 100, name: 'Ibuprofen (carboxyibuprofen metabolite)' },
    { id: 101, name: 'Ibuprofen (2-hydroxyibuprofen metabolite)' },
    { id: 102, name: 'Ibuprofen' },
    { id: 103, name: 'Irinotecan' },
    { id: 104, name: 'SN-38 (Irinotecan Metabolite)' },
    { id: 105, name: 'Ivermectin' },
    { id: 106, name: 'Ketoprofen' },
    { id: 107, name: 'Lactose' },
    { id: 108, name: 'Letrozole' },
    { id: 109, name: 'Levofloxacin' },
    { id: 110, name: 'Levosulpiride' },
    { id: 111, name: 'Lidocaine' },
    { id: 112, name: 'Lidocaine (monoethylglycinexylidide metabolite)' },
    { id: 113, name: 'Lincomycin' },
    { id: 114, name: 'Spectinomycin' },
    { id: 115, name: 'Marbofloxacin' },
    { id: 116, name: 'Ketamine' },
    { id: 117, name: 'Medetomidine' },
    { id: 118, name: 'Meloxicam' },
    { id: 119, name: 'Menbutone' },
    { id: 120, name: 'Mequindox' },
    { id: 121, name: 'Metamizole' },
    { id: 122, name: '4-Amino-antipyrine' },
    { id: 123, name: 'Metarrestin' },
    { id: 124, name: 'Methadone' },
    { id: 125, name: 'Metoclopramide' },
    { id: 126, name: 'Metoprolol tartrate' },
    { id: 127, name: 'Metronidazole' },
    { id: 128, name: 'Metronidazole (hydroxymetronidazole metabolite)' },
    { id: 129, name: 'Midazolam' },
    { id: 130, name: 'Midazolam (1-hydroxymethyl metabolite)' },
    { id: 131, name: 'Minocycline' },
    { id: 132, name: 'Monensin' },
    { id: 133, name: 'Morphine' },
    { id: 134, name: 'Lidocaine (3-hydroxy metabolite)' },
    { id: 135, name: 'Lidocaine (4-hydroxylidocaine metabolite)' },
    { id: 136, name: 'Ketamine (norketamine metabolite)' },
    { id: 137, name: 'Ketamine (dehydronorketamine metabolite)' },
    { id: 138, name: 'Moxidectin' },
    { id: 139, name: 'Moxifloxacin' },
    { id: 140, name: 'Nalbuphine' },
    { id: 141, name: 'Naltrexone' },
    { id: 142, name: 'Naltrexone hydrochloride' },
    { id: 143, name: 'Neomycin sulfate' },
    { id: 144, name: 'Norgestomet' },
    { id: 145, name: 'Novobiocin' },
    { id: 146, name: 'Omeprazole' },
    { id: 147, name: 'Orbifloxacin' },
    { id: 148, name: 'Oxfendazole' },
    { id: 149, name: 'Oxfendazole (fenbendazole sulfone metabolite)' },
    { id: 150, name: 'Oxytetracycline' },
    { id: 151, name: 'PAC-14028' },
    { id: 152, name: 'Pantoprazole' },
    { id: 153, name: 'Paromomycin' },
    { id: 154, name: 'Penicillin G' },
    { id: 155, name: 'Penicillin g benzathine' },
    { id: 156, name: 'Penicillin G potassium' },
    { id: 157, name: 'Phenobarbital' },
    { id: 158, name: 'Pidotimod' },
    { id: 159, name: 'Pirfenidone' },
    { id: 160, name: 'Propofol' },
    { id: 161, name: 'Quinidine' },
    { id: 162, name: 'Quinocetone' },
    { id: 163, name: 'Reltecimod' },
    { id: 164, name: 'Repaglinide' },
    { id: 165, name: 'Rifampin' },
    { id: 166, name: 'Robenacoxib' },
    { id: 167, name: 'Salicylate' },
    { id: 168, name: 'Salicylic acid' },
    { id: 169, name: 'Salinomycin' },
    { id: 170, name: 'Sanguinarine' },
    { id: 171, name: 'dihydrosanguinarine' },
    { id: 172, name: 'Chelerythine' },
    { id: 173, name: 'Sialyllactose' },
    { id: 174, name: 'Sisapronil' },
    { id: 175, name: 'Solithromycin' },
    { id: 176, name: 'Spiramycin' },
    { id: 177, name: 'Sulfacetamide' },
    { id: 178, name: 'Sulfadiazine' },
    { id: 179, name: 'sulfadimethoxine' },
    { id: 180, name: 'Sulfadoxine' },
    { id: 181, name: 'Sulfamerazine' },
    { id: 182, name: 'Sulfameter' },
    { id: 183, name: 'Sulfamethazine' },
    { id: 184, name: 'Sulfamethazine sodium' },
    { id: 185, name: 'Sulfamonomethoxine' },
    { id: 186, name: 'Sulfamoxole' },
    { id: 187, name: 'Sulfanilamide' },
    { id: 188, name: 'Sulfaquinoxaline' },
    { id: 189, name: 'Sulfathiazole' },
    { id: 190, name: 'Sulfisomidine' },
    { id: 191, name: 'Sulfisoxazole' },
    { id: 192, name: 'T-2 toxin' },
    { id: 193, name: 'T-2 toxin (HT-2 toxin metabolite)' },
    { id: 194, name: 'T-2 toxin (T-2 triol metabolite)' },
    { id: 195, name: 'Tapentadol' },
    { id: 196, name: 'Tetracycline' },
    { id: 197, name: 'Tetrahydrocannabinol' },
    { id: 198, name: 'Celecoxib' },
    { id: 199, name: 'Thalidomide' },
    { id: 200, name: 'Thiamphenicol' },
    { id: 201, name: 'Thiamphenicol (glucuronide metabolite)' },
    { id: 202, name: 'Thiamylal' },
    { id: 203, name: 'Thiopental' },
    { id: 204, name: 'Thymoquinone' },
    { id: 205, name: 'Tildipirosin' },
    { id: 206, name: 'Tocopherol dl-alpha-tocopheryl acetate' },
    { id: 207, name: 'Tolfenamic acid' },
    { id: 208, name: 'Tramadol' },
    { id: 209, name: 'Tramadol (M1 metabolite)' },
    { id: 210, name: 'Triclabendazole (sulfoxide metabolite)' },
    { id: 211, name: 'Triclabendazole (sulfone metabolite)' },
    { id: 212, name: 'Trimethoprim' },
    { id: 213, name: 'Trovafloxacin' },
    { id: 214, name: 'Tulathromycin' },
    { id: 215, name: 'Tylosin' },
    { id: 216, name: 'Tylosin D' },
    { id: 217, name: 'Tylosin A' },
    { id: 218, name: 'Valnemulin' },
    { id: 219, name: 'Varfarin' },
    { id: 220, name: 'Vigabatrin' },
    { id: 221, name: 'Vincamine' },
    { id: 222, name: 'Voriconazole' },
    { id: 223, name: 'Zearalenone' },
    { id: 224, name: 'Zolmitriptan' }
];

export default drugData;
